"""add organization_ipo table

Revision ID: 321de048330d
Revises: 7d5fb9408933
Create Date: 2026-05-07 22:48:36.861653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '321de048330d'
down_revision: Union[str, None] = '7d5fb9408933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_ipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('ipo_score', sa.Float(), nullable=False),
    sa.Column('d_score', sa.Float(), nullable=False),
    sa.Column('a_score', sa.Float(), nullable=False),
    sa.Column('e_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'year', name='uq_org_ipo_year')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_ipo')
    # ### end Alembic commands ###
