"""Add created_at to InvestmentReport model

Revision ID: 4d266c4094fb
Revises: dc50886759dc
Create Date: 2025-11-11 19:00:54.754491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d266c4094fb'
down_revision: Union[str, None] = 'dc50886759dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_report', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_report', 'created_at')
    # ### end Alembic commands ###
