"""add_analytics_fields

Revision ID: 7a1ddc21a3a6
Revises: 4d266c4094fb
Create Date: 2025-11-20 18:51:50.150338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a1ddc21a3a6'
down_revision: Union[str, None] = '4d266c4094fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_report', sa.Column('quarter', sa.Integer(), nullable=False))
    op.add_column('investment_report', sa.Column('total_investment', sa.Float(), nullable=False))
    op.add_column('investment_report', sa.Column('budget_federal', sa.Float(), nullable=False))
    op.add_column('investment_report', sa.Column('budget_regional', sa.Float(), nullable=False))
    op.add_column('investment_report', sa.Column('own_funds', sa.Float(), nullable=False))
    op.alter_column('investment_report', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('investment_report', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_investment_report_created_by_user_id', table_name='investment_report')
    op.add_column('organization', sa.Column('municipality', sa.String(length=255), nullable=True))
    op.add_column('organization', sa.Column('org_type', sa.String(length=50), nullable=True))
    op.add_column('organization', sa.Column('coordinates', sa.JSON(), nullable=True))
    op.add_column('organization', sa.Column('cluster_group', sa.Integer(), nullable=True))
    op.alter_column('organization', 'inn',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=12),
               existing_nullable=False)
    op.create_index(op.f('ix_organization_municipality'), 'organization', ['municipality'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_municipality'), table_name='organization')
    op.alter_column('organization', 'inn',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('organization', 'cluster_group')
    op.drop_column('organization', 'coordinates')
    op.drop_column('organization', 'org_type')
    op.drop_column('organization', 'municipality')
    op.create_index('ix_investment_report_created_by_user_id', 'investment_report', ['created_by_user_id'], unique=False)
    op.alter_column('investment_report', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('investment_report', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('investment_report', 'own_funds')
    op.drop_column('investment_report', 'budget_regional')
    op.drop_column('investment_report', 'budget_federal')
    op.drop_column('investment_report', 'total_investment')
    op.drop_column('investment_report', 'quarter')
    # ### end Alembic commands ###
